#pragma once

// Generated by scripts/gen-nfc-tables.py from Unicode 16.0.0. Do not edit by hand.
//
// Supporting data for detail/unicode/nfc_ascii.hpp, which answers exactly one
// question: after NFC, which printable-ASCII characters are still visible? See
// that header, and the generator, for why this is not a general NFC
// implementation and must never be reused as one.
//
// Stability: the Unicode Normalization Stability Policy freezes the composition
// table, the singleton mappings and the mark decompositions below, so those can
// never change. Only the combining-class ranges grow, as new scripts are
// encoded. A stale range can only matter for a value that mixes a printable
// ASCII base with a combining mark from a script this table predates, which no
// UUID, machine-id, DMI string, SMBIOS string or host name contains.

#include <cstddef>
#include <cstdint>

namespace moonbase::detail::unicode::tables {

inline constexpr const char* unicode_version = "16.0.0";

// ---------------------------------------------------------------------------
// Canonical combining class, as run-collapsed ranges over the code points with
// a non-zero class. Needed both to tell a combining mark from a starter and to
// find the head of each equal-class run when testing whether a mark is blocked.

struct combining_class_range {
    char32_t first;
    char32_t last;
    std::uint8_t combining_class;
};

inline constexpr combining_class_range combining_class_ranges[] = {
    {0x0300,0x0314,230}, {0x0315,0x0315,232}, {0x0316,0x0319,220}, {0x031A,0x031A,232}, {0x031B,0x031B,216}, {0x031C,0x0320,220},
    {0x0321,0x0322,202}, {0x0323,0x0326,220}, {0x0327,0x0328,202}, {0x0329,0x0333,220}, {0x0334,0x0338,1}, {0x0339,0x033C,220},
    {0x033D,0x0344,230}, {0x0345,0x0345,240}, {0x0346,0x0346,230}, {0x0347,0x0349,220}, {0x034A,0x034C,230}, {0x034D,0x034E,220},
    {0x0350,0x0352,230}, {0x0353,0x0356,220}, {0x0357,0x0357,230}, {0x0358,0x0358,232}, {0x0359,0x035A,220}, {0x035B,0x035B,230},
    {0x035C,0x035C,233}, {0x035D,0x035E,234}, {0x035F,0x035F,233}, {0x0360,0x0361,234}, {0x0362,0x0362,233}, {0x0363,0x036F,230},
    {0x1AB0,0x1AB4,230}, {0x1AB5,0x1ABA,220}, {0x1ABB,0x1ABC,230}, {0x1ABD,0x1ABD,220}, {0x1ABF,0x1AC0,220}, {0x1AC1,0x1AC2,230},
    {0x1AC3,0x1AC4,220}, {0x1AC5,0x1AC9,230}, {0x1ACA,0x1ACA,220}, {0x1ACB,0x1ACE,230}, {0x1DC0,0x1DC1,230}, {0x1DC2,0x1DC2,220},
    {0x1DC3,0x1DC9,230}, {0x1DCA,0x1DCA,220}, {0x1DCB,0x1DCC,230}, {0x1DCD,0x1DCD,234}, {0x1DCE,0x1DCE,214}, {0x1DCF,0x1DCF,220},
    {0x1DD0,0x1DD0,202}, {0x1DD1,0x1DF5,230}, {0x1DF6,0x1DF6,232}, {0x1DF7,0x1DF8,228}, {0x1DF9,0x1DF9,220}, {0x1DFA,0x1DFA,218},
    {0x1DFB,0x1DFB,230}, {0x1DFC,0x1DFC,233}, {0x1DFD,0x1DFD,220}, {0x1DFE,0x1DFE,230}, {0x1DFF,0x1DFF,220}, {0x20D0,0x20D1,230},
    {0x20D2,0x20D3,1}, {0x20D4,0x20D7,230}, {0x20D8,0x20DA,1}, {0x20DB,0x20DC,230}, {0x20E1,0x20E1,230}, {0x20E5,0x20E6,1},
    {0x20E7,0x20E7,230}, {0x20E8,0x20E8,220}, {0x20E9,0x20E9,230}, {0x20EA,0x20EB,1}, {0x20EC,0x20EF,220}, {0x20F0,0x20F0,230},
    {0xFE20,0xFE26,230}, {0xFE27,0xFE2D,220}, {0xFE2E,0xFE2F,230},
};

inline constexpr std::size_t combining_class_range_count =
    sizeof(combining_class_ranges) / sizeof(combining_class_ranges[0]);

// ---------------------------------------------------------------------------
// The 26 combining marks that can form a primary composite with a printable
// ASCII base, and a bitmask per base saying which. All of them fall in
// U+0300..U+0338, so a small index array resolves a mark to its bit in O(1).

inline constexpr char32_t composing_mark_first = 0x0300;
inline constexpr char32_t composing_mark_last = 0x0338;

inline constexpr std::int8_t composing_mark_index[] = {
    0, 1, 2, 3, 4, -1, 5, 6, 7, 8, 9, 10, 11, -1, -1, 12,
    -1, 13, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1,
    -1, -1, -1, 15, 16, 17, 18, 19, 20, -1, -1, -1, -1, 21, 22, -1,
    23, 24, -1, -1, -1, -1, -1, -1, 25,
};

// Indexed by (base - 0x20) for base in U+0020..U+007E. Bit i corresponds to the
// mark whose composing_mark_index value is i.
inline constexpr std::uint32_t composition_masks[] = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x02000000, 0x02000000,
    0x02000000, 0x00000000, 0x00000000, 0x0012BBFF, 0x01008040, 0x00080846,
    0x01288840, 0x00B8B9FF, 0x00000040, 0x00080876, 0x004888C4, 0x0090B9FF,
    0x00000004, 0x01088802, 0x01288802, 0x00008042, 0x0128884B, 0x0010FDFF,
    0x00000042, 0x00000000, 0x0108B842, 0x000C8846, 0x012C8840, 0x00B1FFBF,
    0x00008008, 0x000080C7, 0x000000C0, 0x000081DF, 0x01008846, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x0012BBFF,
    0x01008040, 0x00080846, 0x01288840, 0x00B8B9FF, 0x00000040, 0x00080876,
    0x014888C4, 0x0090B9BF, 0x00000804, 0x01088802, 0x01288802, 0x00008042,
    0x0128884B, 0x0010FDFF, 0x00000042, 0x00000000, 0x0108B842, 0x000C8846,
    0x012C88C0, 0x00B1FFBF, 0x00008008, 0x000082C7, 0x000000C0, 0x000083DF,
    0x01008846, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

inline constexpr char32_t composition_mask_first = 0x0020;
inline constexpr char32_t composition_mask_last = 0x007E;

// The distinct combining classes those marks use. A mark is blocked only by an
// earlier mark of the same class, so a class absent from this list can neither
// compose with an ASCII base nor block something that would, and the cluster
// walk skips it. Position in this array is the bit used to remember that the
// class has already been seen in the current cluster.
inline constexpr std::uint8_t composing_mark_classes[] = {
    1, 202, 216, 220, 230,
};

inline constexpr std::size_t composing_mark_class_count =
    sizeof(composing_mark_classes) / sizeof(composing_mark_classes[0]);

// ---------------------------------------------------------------------------
// Non-ASCII code points whose NFC form is a single printable-ASCII character.
// These are singleton decompositions, which are always composition-excluded, so
// NFC leaves the ASCII result exposed and it must survive the filter.

struct ascii_singleton {
    char32_t from;
    char32_t to;
};

inline constexpr ascii_singleton ascii_singletons[] = {
    {0x037E,0x003B}, {0x1FEF,0x0060}, {0x212A,0x004B},
};

inline constexpr std::size_t ascii_singleton_count =
    sizeof(ascii_singletons) / sizeof(ascii_singletons[0]);

// ---------------------------------------------------------------------------
// Combining marks with a canonical decomposition of their own. They must be
// expanded in place before the blocking analysis, or a mark that decomposes to
// a composing one would fail to annihilate its base.

struct mark_decomposition {
    char32_t from;
    char32_t to[2];
    std::uint8_t length;
};

inline constexpr mark_decomposition mark_decompositions[] = {
    {0x0340,{0x0300,0x0000},1}, {0x0341,{0x0301,0x0000},1},
    {0x0343,{0x0313,0x0000},1}, {0x0344,{0x0308,0x0301},2},
};

inline constexpr std::size_t mark_decomposition_count =
    sizeof(mark_decompositions) / sizeof(mark_decompositions[0]);

} // namespace moonbase::detail::unicode::tables
