#!/usr/bin/env bash
#
# Refresh the vendored device-fingerprint conformance artifacts from the canonical
# copies published with @moonbase.sh/licensing:
#
#   FINGERPRINT_SPEC.md            <- packages/licensing/FINGERPRINT_SPEC.md
#   tests/vectors/fingerprint-vectors.json  <- packages/licensing/fingerprint-vectors.json
#
# The vectors are the executable half of the spec: when the prose and the vectors
# disagree, the vectors win, because they are what every SDK can actually run.
# This SDK ships its own copies so the test suite works with no npm, no network
# and no sibling checkout.
#
# The spec is not copied byte-for-byte. It gains a provenance header, and its
# relative links to ./fingerprint-vectors.json are rewritten to the path the file
# actually lives at here. Both transforms are applied deterministically below so
# --check can verify the result rather than just the source.
#
# CI runs this with --check. Unlike sync-juce-module.sh, a missing source is not
# an error: the JavaScript repo is not present on a CI runner, so --check can only
# compare when someone runs it locally. In CI the authority is instead the npm
# package, which the fingerprint-parity workflow points --from at.
#
# Usage:
#   scripts/sync-fingerprint-vectors.sh [--check] [--vectors-only] [--from <path>]
#
# --vectors-only skips the spec comparison. The parity workflow uses it because it
# points --from at an *installed npm package*, and this SDK may legitimately
# implement a spec revision that has not been published yet (it did so for the
# scoped-identity extension). The vectors are what decides conformance, so they
# must always match; the prose can lead.
#
# --from names the *vectors* file; the spec is looked up beside it. The default
# source is $MOONBASE_JS_ROOT (or ../moonbase.js next to this repo) plus
# /packages/licensing/.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
vectors_dst="${repo_root}/tests/vectors/fingerprint-vectors.json"
spec_dst="${repo_root}/FINGERPRINT_SPEC.md"
js_root="${MOONBASE_JS_ROOT:-${repo_root}/../moonbase.js}"
vectors_src="${js_root}/packages/licensing/fingerprint-vectors.json"

check_only=0
vectors_only=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --check)
            check_only=1
            shift
            ;;
        --vectors-only)
            vectors_only=1
            shift
            ;;
        --from)
            if [[ $# -lt 2 ]]; then
                echo "error: --from needs a path" >&2
                exit 2
            fi
            vectors_src="$2"
            shift 2
            ;;
        *)
            echo "error: unknown argument '$1'" >&2
            echo "usage: sync-fingerprint-vectors.sh [--check] [--vectors-only] [--from <path>]" >&2
            exit 2
            ;;
    esac
done

spec_src="$(dirname "${vectors_src}")/FINGERPRINT_SPEC.md"

if [[ ! -f "${vectors_src}" ]]; then
    if [[ "${check_only}" -eq 1 ]]; then
        echo "note: canonical vectors not found at ${vectors_src}; skipping the comparison."
        echo "      set MOONBASE_JS_ROOT or pass --from to check against a local checkout."
        exit 0
    fi
    echo "error: canonical vectors not found at ${vectors_src}" >&2
    echo "       set MOONBASE_JS_ROOT or pass --from <path>." >&2
    exit 1
fi

# Render the vendored spec: provenance header, then the canonical text with its
# relative vector links repointed at this repo's layout.
render_spec() {
    cat <<'HDR'
<!--
  Vendored copy of the Moonbase device fingerprint specification, published with
  @moonbase.sh/licensing. This SDK implements it from 4.0.0 onward.

  The canonical version ships inside the npm package
  (node_modules/@moonbase.sh/licensing/FINGERPRINT_SPEC.md). If this copy and the
  canonical one disagree, the canonical one wins. If the spec and
  tests/vectors/fingerprint-vectors.json disagree, the vectors win: they are what
  every SDK can actually execute, and they are what this SDK's conformance suite
  runs (tests/fingerprint_spec_tests.cpp).

  It is vendored rather than linked because this SDK is consumed as a git
  submodule or via FetchContent by developers who often have no npm and sometimes
  no network, and because the JUCE module's promise is to be self-contained.

  Generated by scripts/sync-fingerprint-vectors.sh. Do not edit by hand: the
  relative links to the conformance vectors are rewritten to this repo's layout,
  and a hand edit would be lost on the next sync.
-->

HDR
    # ./fingerprint-vectors.json lives at tests/vectors/ here, so the canonical
    # sibling-file links would 404.
    sed 's|](\./fingerprint-vectors\.json)|](tests/vectors/fingerprint-vectors.json)|g' "$1"
}

vectors_in_sync=0
spec_in_sync=0

if [[ -f "${vectors_dst}" ]] && diff -q "${vectors_src}" "${vectors_dst}" >/dev/null 2>&1; then
    vectors_in_sync=1
fi

if [[ "${vectors_only}" -eq 1 ]]; then
    spec_in_sync=1
elif [[ -f "${spec_src}" ]]; then
    if [[ -f "${spec_dst}" ]] && diff -q <(render_spec "${spec_src}") "${spec_dst}" >/dev/null 2>&1; then
        spec_in_sync=1
    fi
else
    # An --from pointing at an npm install may not ship the spec; the vectors are
    # the part that decides conformance, so treat the spec as satisfied.
    echo "note: no FINGERPRINT_SPEC.md beside ${vectors_src}; checking the vectors only."
    spec_in_sync=1
fi

if [[ "${check_only}" -eq 1 ]]; then
    status=0
    if [[ "${vectors_in_sync}" -eq 0 ]]; then
        echo "error: ${vectors_dst} differs from ${vectors_src}." >&2
        status=1
    fi
    if [[ "${spec_in_sync}" -eq 0 ]]; then
        echo "error: ${spec_dst} differs from the rendered ${spec_src}." >&2
        status=1
    fi
    if [[ "${status}" -ne 0 ]]; then
        echo "       run scripts/sync-fingerprint-vectors.sh and commit the result," >&2
        echo "       then re-run the conformance tests: a changed vector file may mean" >&2
        echo "       the spec moved and this SDK has to move with it." >&2
        exit 1
    fi
    echo "fingerprint spec and vectors are in sync."
    exit 0
fi

mkdir -p "$(dirname "${vectors_dst}")"
cp "${vectors_src}" "${vectors_dst}"
echo "synced ${vectors_src} -> ${vectors_dst}"

if [[ "${vectors_only}" -eq 0 && -f "${spec_src}" ]]; then
    render_spec "${spec_src}" > "${spec_dst}"
    echo "synced ${spec_src} -> ${spec_dst} (provenance header + rewritten vector links)"
fi
